ValgRepresentanter/Controllers/ToolsController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ToolsController.cs" company="NTB">
//   NTB
// </copyright>
// <summary>
//   The tools controller.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace ElectionCandidates.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    using ElectionCandidates.Classes;
    using ElectionCandidates.Models;
    using ElectionCandidates.Models.DataModels;

    /// <summary>
    /// The tools controller.
    /// </summary>
    public class ToolsController : Controller
    {
        /// <summary>
        ///     The index.
        /// </summary>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        ///     The add parliament periods.
        /// </summary>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult AddParliamentPeriods()
        {
            return View();
        }

        /// <summary>
        /// The get parliament periods.
        /// </summary>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult GetParliamentPeriods()
        {
            ToolsModels toolsModel = new ToolsModels();
            List<ParliamentPeriod> parliamentPeriods = toolsModel.GetParliamentPeriods();

            ParliamentDataModel parliamentDataModel = new ParliamentDataModel();
            parliamentDataModel.InsertParliamentPeriods(parliamentPeriods);

            return View("Index");
        }

        /// <summary>
        /// The check current candidates.
        /// </summary>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult CheckCurrentCandidates()
        {
            ToolsModels toolsModel = new ToolsModels();
            List<Candidate> currentCandidates = toolsModel.GetCurrentParliamentMembersFromParliament();
            Session["CurrentCandidates"] = currentCandidates;
            CandidatesModels candidatesModels = new CandidatesModels();
            List<Candidate> candidates = candidatesModels.GetRepresentanter(DateTime.Today.Year);
            candidates = toolsModel.MatchCurrentParliamentAgainstCandidateList(candidates, currentCandidates);
            return this.View("CheckCurrentCandidates", candidates);
        }

        /// <summary>
        /// The update checked current candidates.
        /// </summary>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult UpdateCheckedCurrentCandidates()
        {
            ToolsModels toolsModel = new ToolsModels();
            List<Candidate> currentCandidates = toolsModel.GetCurrentParliamentMembersFromParliament();
            CandidatesModels candidatesModels = new CandidatesModels();
            List<Candidate> candidates = candidatesModels.GetRepresentanter(DateTime.Today.Year);
            candidates = toolsModel.MatchCurrentParliamentAgainstCandidateList(candidates, currentCandidates);

            if (candidates != null)
            {
                toolsModel.UpdateCandidates(candidates);
            }

            return this.View("Index");
        }

        /// <summary>
        /// The check candidate picture.
        /// </summary>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult CheckCandidatePicture()
        {
            CandidatesModels candidatesModels = new CandidatesModels();
            List<Candidate> candidates = candidatesModels.GetRepresentanter(DateTime.Today.Year);
            
            ToolsModels toolsModel = new ToolsModels();
            List<Candidate> correctedCandidates = toolsModel.CheckCandidatesPicture(candidates);

            toolsModel.UpdateCandidates(correctedCandidates);

            return this.View("CheckCandidatePicture", correctedCandidates);
        }

        /// <summary>
        /// The check candidate picture.
        /// </summary>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult CheckAndUploadCandidatePicture()
        {
            CandidatesModels candidatesModels = new CandidatesModels();
            List<Candidate> candidates = candidatesModels.GetRepresentanter(DateTime.Today.Year);

            return this.View("CheckAndUploadCandidatePicture", candidates);
        }

        public ActionResult GetCurrentParliamentMembers()
        {
            ToolsModels toolsModel = new ToolsModels();
            List<Candidate> currentCandidates = toolsModel.GetCurrentParliamentMembersFromParliament();

            return this.View("GetCurrentParliamentMembers", currentCandidates);
        }
    }
}

ValgRepresentanter/Views/Tools/AddParliamentPeriods.cshtml
@{
    ViewBag.Title = "AddParliamentPeriods";
}

<h2>Hent Stortingsperioder</h2>
<span>Ved å trykke på <a href="GetParliamentPeriods">denne</a> linken går vi til data.stortinget.no for å hente stortingsperioder.</span><br/>

ValgRepresentanter/Views/Tools/CheckAndUploadCandidatePicture.cshtml
@using ElectionCandidates.Classes
@model List<Candidate>

@{
    ViewBag.Title = "CheckAndUploadCandidatePicture";
}

<h2>CheckAndUploadCandidatePicture</h2>

<table>
<thead>
<tr>
    <th style="width: 200px;">Navn</th>
    <th style="width: 200px;">Parti</th>
    <th style="width: 200px;">Fylke</th>
    <th style="width: 100px;">Bilde</th>
</tr>
</thead>
    <tbody>
        @{
        foreach (Candidate representant in Model)
        {
        var repid = "rep" + representant.CandidateId;
        var dialog = "dialog" + representant.CandidateId;
        var slette = "Slette " + representant.FirstName + " " + representant.LastName;

        var partyCode = representant.PoliticalPartyCode;
        
        <tr>
            <td>@representant.FirstName @representant.LastName</td>
            <td>@representant.PoliticalParty (@partyCode)</td>
            <td>@representant.County</td>
            <td>
                @{
                    if (representant.Picture != null)
                    {
                        string serverPath = Server.MapPath(Url.Content("~/Content/picturecheck/"));
                        string[] fileparts = representant.Picture.Split('_');
                        string path = serverPath + fileparts[0] + @"\" + fileparts[1] + @"\" + representant.Picture.Replace("_org.png", "_org200.png");
                        FileInfo fileInfo = new FileInfo(path);
                        if (!fileInfo.Exists)
                        {
                            <span>Bilde mangler!</span>
                        }
                    }
                }
            </td>
        </tr>
        }
        }
    </tbody>
</table>

ValgRepresentanter/Views/Tools/CheckCandidatePicture.cshtml
@model List<ElectionCandidates.Classes.Candidate>

@{
    ViewBag.Title = "CheckCandidatePicture";
}

<h2>CheckCandidatePicture</h2>
<table>
    <thead>
        <tr>
            <th>Navn</th>
            <th>Bilde</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (ElectionCandidates.Classes.Candidate candidate in Model)
            {
                <tr>
                    <td>@candidate.FirstName @candidate.LastName</td>
                    <td>@candidate.Picture</td>
                </tr>
            }
        }
    </tbody>
</table>

ValgRepresentanter/Views/Tools/CheckCurrentCandidates.cshtml
@using ElectionCandidates.Classes
@model List<Candidate>

@{
    ViewBag.Title = "CheckCurrentCandidates";

    List<Candidate> currentCandidates = (List<Candidate>)this.Session["CurrentCandidates"];
    
}

<h2>CurrentCandidates</h2>
<span>Antall kandidater i XML: @currentCandidates.Count()</span>
<table style="border: 1px solid #dddddd;">
    <thead>
        <tr>
            <th>Representant</th>
            <th>Fødselsdato</th>
            <th>Stortingsperioder</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (Candidate candidate in Model)
            {
                <tr>
                    <td>@candidate.FirstName @candidate.LastName</td>
                    <td>@candidate.BirthDate</td>
                    <td>
                        @{
                            if (candidate.ParliamentPeriods != null)
                            {
                                foreach (ParliamentPeriod parliamentPeriod in candidate.ParliamentPeriods)
                                {
                                    @parliamentPeriod.ParliamentPeriodId
                                    
                                    <br />
                                }
                            }
                        }
                    </td>
                </tr>
            }
        }
    </tbody>
    <tfoot>
        <tr style="background-color:gray">
            <td colspan="3">
                @Html.ActionLink("Oppdater data", "UpdateCheckedCurrentCandidates", "Tools")  
            </td>
        </tr>
    </tfoot>
</table>

ValgRepresentanter/Views/Tools/GetCurrentParliamentMembers.cshtml
@using ElectionCandidates.Classes
@model List<Candidate>


<span>Antall kandidater i XML: @Model.Count()</span>
<table style="border: 1px solid #dddddd;">
    <thead>
        <tr>
            <th>Representant</th>
            <th>Parti</th>
            <th>Stortingsperiode</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (Candidate candidate in Model)
            {
                <tr>
                    <td>@candidate.FirstName @candidate.LastName</td>
                    <td>@candidate.PoliticalParty</td>
                    <td>@candidate.ParliamentPeriods[0].ParliamentPeriodId</td>
                </tr>
            }
        }
    </tbody>
    <tfoot>
        <tr style="background-color:gray">
            <td colspan="3">&nbsp;</td>
        </tr>
    </tfoot>
</table>

ValgRepresentanter/Views/Tools/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Verktøy</h2>
<ul>
    <li>
        @Html.ActionLink("Legg inn Stortingsperioder", "AddParliamentPeriods", "Tools")        
    </li>
    <li>
        @Html.ActionLink("Sjekk dagens storting mot database", "CheckCurrentCandidates", "Tools")        
    </li>
    <li>
        @Html.ActionLink("Hent dagens storting", "GetCurrentParliamentMembers", "Tools")        
    </li>
    <li>
        @Html.ActionLink("Sjekk om representanten har bilde", "CheckCandidatePicture", "Tools")
    </li>
    <li>
        @Html.ActionLink("Sjekk og last opp behandlede bilder", "CheckAndUploadCandidatePicture", "Tools")
    </li>
</ul>